import Head from "next/head";
import AllPosts from "@/components/posts/all-posts";

const postsObj = [
  {
    title: "Getting Started - NextJs",
    image: "getting-started-nextjs.png",
    excerpt:
      "Nextjs is the react framework for the production - it helps creating full stack React apps and ships with the built in SSR.",
    date: "04/16/2023",
    slug: "getting-started-with-nextjs",
  },
  {
    title: "Mastering Js",
    image: "mastering-js-thumb.png",
    excerpt: "React Js Masters in few weeks. Just click to apply now!",
    date: "04/20/2023",
    slug: "mastering-javascript",
  },
];

function AllPostsPage() {
  return (
    <>
      <Head>
        <title>My Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AllPosts posts={postsObj} />;
    </>
  );
}

export default AllPostsPage;
