import Head from "next/head";
import ContactForm from "@/components/contact/contact-form";

function ContactPage(props) {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ContactForm />
    </>
  );
}

export default ContactPage;
