import Head from "next/head";
import Hero from "@/components/home-page/hero";
import FeaturedPosts from "@/components/home-page/featured-posts";
import { getFeaturedPosts } from "@/lib/posts-util";
import styles from "@/styles/Home.module.css";

export default function Home(props) {
  const posts = [
    {
      title: "Getting Started - NextJs",
      image: "getting-started-nextjs.png",
      excerpt:
        "Nextjs is the react framework for the production - it helps creating full stack React apps and ships with the built in SSR.",
      date: "04/16/2023",
      slug: "getting-started-with-nextjs",
    },
    {
      title: "Mastering Js",
      image: "mastering-js-thumb.png",
      excerpt: "React Js Masters in few weeks. Just click to apply now!",
      date: "04/20/2023",
      slug: "mastering-javascript",
    },
  ];
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <FeaturedPosts posts={props.posts} />
      </main>
    </>
  );
}

export function getStaticProps() {
  const featuredPosts = getFeaturedPosts();

  return {
    props: {
      posts: featuredPosts,
    },
  };
}
